'use client';
import {useState} from 'react';
import * as Dialog from '@radix-ui/react-dialog';
import {Plus,X,ArrowUpRight,Flame,Utensils,Check} from 'lucide-react';
import {products,money,type Product} from '@/lib/catalog';
import {useCart} from './cart-provider';
function ProductCard({product,index}:{product:Product;index:number}){
 const {add,ready}=useCart(),[open,setOpen]=useState(false),[sauces,setSauces]=useState<string[]>(product.sauces);
 const choose=(s:string)=>setSauces(old=>old.includes(s)?old.filter(x=>x!==s):[...old,s]);
 return <article className={`product-card ${product.tone}`}><div className="product-top"><span className="product-number">0{index+1}</span><span className="product-category">{index===0?<Utensils size={17}/>:<Flame size={17}/>} {index===0?'El tradicional':'El de la plancha'}</span></div><div className="product-main"><h3>{product.name}</h3><p className="product-description">{product.description}</p><div className="ingredients"><h4>¿Qué lleva?</h4><p>{product.ingredients.join(' · ')}</p></div><Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger className="text-button">Ingredientes y salsas <ArrowUpRight size={16}/></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="product-dialog"><Dialog.Close aria-label="Cerrar detalles" className="icon-btn dialog-close"><X size={20}/></Dialog.Close><span className={`product-number ${product.tone}`}>0{index+1}</span><Dialog.Title>{product.name}</Dialog.Title><Dialog.Description>{product.description}</Dialog.Description><h3>Ingredientes</h3><ul className="ingredient-list">{product.ingredients.map(i=><li key={i}>{i}</li>)}</ul><h3>Salsas</h3>{product.sauces.length?<fieldset className="sauce-options"><legend className="sr-only">Elige las salsas para tu perro</legend>{product.sauces.map(s=><label key={s}><input type="checkbox" checked={sauces.includes(s)} onChange={()=>choose(s)}/><span>{s}</span><Check size={16}/></label>)}</fieldset>:<p>Pregunta por las salsas disponibles al confirmar tu pedido.</p>}<p className="allergy-note">¿Tienes alguna alergia? Consúltanos antes de pedir.</p><button className="button primary full" disabled={!ready} onClick={e=>{add(product.id,sauces,e.currentTarget);setOpen(false);}}>Agregar · {money(product.price)} <Plus size={19}/></button></Dialog.Content></Dialog.Portal></Dialog.Root></div><div className="product-bottom"><div><span className="price-label">Por perro</span><strong>{money(product.price)}</strong></div><button className="add-button" aria-label={`Agregar ${product.name}`} disabled={!ready} onClick={e=>add(product.id,sauces,e.currentTarget)}><Plus size={21}/><span>Agregar</span></button></div></article>;
}
export function Menu(){return <section id="menu" className="wrap section"><div className="section-head"><div><div className="eyebrow">El menú de los compas</div><h2>Dos formas de<br className="mobile-break"/> armar el parche.</h2></div><p>Elige tu perro. Nosotros ponemos el cariño.</p></div><div className="menu-grid">{products.map((p,i)=><ProductCard key={p.id} product={p} index={i}/>)}</div><p className="menu-footnote">Nos estrenamos el 2 de octubre. Confirma disponibilidad y domicilio antes de cerrar tu pedido.</p></section>;}
