'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import * as Dialog from '@radix-ui/react-dialog';
import {ShoppingBag,X,Plus,Minus,Trash2,ArrowRight,ArrowUpRight,MapPin,MessageCircle,Check,Bike} from 'lucide-react';
import {useCart} from './cart-provider';
import {business,productById,subtotal,money,whatsappUrl} from '@/lib/catalog';
export function WhatsAppIcon({size=22}:{size?:number}){return <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.298.447-.447.149-.149.198-.248.297-.447.099-.198.05-.372-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347M12 2a10 10 0 0 0-8.66 15L2 22l5.12-1.34A10 10 0 1 0 12 2m0 18a8 8 0 0 1-4.1-1.13l-.35-.21-3.04.8.81-2.96-.23-.37A8 8 0 1 1 12 20"/></svg>}
export function WhatsAppLink({className='',children}:{className?:string;children?:React.ReactNode}){
 const url=whatsappUrl('Hola, me gustaría pedir en Los Compas.');
 if(url)return <a href={url} target="_blank" rel="noopener noreferrer" className={className} aria-label="Pedir por WhatsApp"><WhatsAppIcon/>{children}</a>;
 return <Dialog.Root><Dialog.Trigger className={className} aria-label="Consultar pedidos por WhatsApp"><WhatsAppIcon/>{children}</Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="small-dialog"><Dialog.Close className="dialog-close icon-btn" aria-label="Cerrar"><X size={20}/></Dialog.Close><MessageCircle size={30}/><Dialog.Title>Nos hablamos muy pronto.</Dialog.Title><Dialog.Description>Estamos preparando nuestro canal de pedidos. El WhatsApp estará disponible para la apertura.</Dialog.Description><Dialog.Close className="button yellow">Entendido <Check size={18}/></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
export function CartLines(){const {lines,quantity}=useCart();return <div className="cart-lines">{lines.map(line=>{const p=productById(line.productId)!;return <article className="cart-line" key={line.key}><div className={`mini-product ${p.tone}`}><ShoppingBag size={25}/></div><div className="line-details"><h3>{p.name}</h3><p>{p.sauces.length?(line.sauces.join(', ')||'Sin salsas'):'Salsas a confirmar'}</p><strong>{money(p.price*line.quantity)}</strong><div className="quantity"><button aria-label={`Quitar uno de ${p.name}`} onClick={()=>quantity(line.key,line.quantity-1)}><Minus size={15}/></button><span aria-label="Cantidad">{line.quantity}</span><button aria-label={`Añadir uno de ${p.name}`} disabled={line.quantity>=20} onClick={()=>quantity(line.key,line.quantity+1)}><Plus size={15}/></button></div></div><button className="remove" aria-label={`Eliminar ${p.name}`} onClick={()=>quantity(line.key,0)}><Trash2 size={16}/></button></article>;})}</div>;}
export function Header(){const cart=useCart(),pathname=usePathname();return <><a className="skip-link" href="#contenido">Saltar al contenido</a><div className="topbar"><MapPin size={13}/><span>{business.address} · {business.landmark}</span></div><header className="header"><div className="wrap"><Link href="/" aria-label="Los Compas, inicio"><img className="brand-mini" src="/brand/logo-compacto.svg" alt="Los Compas" width="106" height="64"/></Link><nav className="nav" aria-label="Navegación principal"><Link href="/#menu">El menú</Link><Link href="/#domicilios" className="desktop-link">Domicilios</Link><Link href="/pagar" className={`desktop-link ${pathname==='/pagar'?'active':''}`}>Tu pedido</Link><Dialog.Root open={cart.open} onOpenChange={cart.setOpen}><Dialog.Trigger asChild><button id="cart-trigger" className="icon-btn cart-trigger" aria-label={`Abrir carrito, ${cart.count} productos`}><ShoppingBag size={21}/>{cart.count>0&&<span className="cart-count" key={cart.count}>{cart.count}</span>}</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="overlay"/><Dialog.Content className="cart-drawer"><div className="drawer-header"><div><div className="eyebrow">El parche va tomando forma</div><Dialog.Title>Tu pedido <span>({cart.count})</span></Dialog.Title></div><Dialog.Close className="icon-btn" aria-label="Cerrar carrito"><X size={20}/></Dialog.Close></div><Dialog.Description className="sr-only">Revisa tus perros, salsas y cantidades antes de continuar.</Dialog.Description>{cart.lines.length?<><div className="drawer-body"><CartLines/></div><div className="drawer-footer"><div className="total-row"><span>Subtotal</span><strong>{money(subtotal(cart.lines))}</strong></div><p>El valor del domicilio se confirma según tu dirección.</p><Dialog.Close asChild><Link className="button primary full" href="/pagar">Continuar con mi pedido <ArrowRight size={18}/></Link></Dialog.Close><Dialog.Close className="text-button full">Seguir viendo el menú</Dialog.Close></div></>:<div className="empty-cart"><ShoppingBag size={44} strokeWidth={1.3}/><h3>Aquí empieza el parche.</h3><p>Todavía no has agregado ningún perro.</p><Dialog.Close asChild><Link href="/#menu" className="button yellow">Conocer el menú <ArrowRight size={18}/></Link></Dialog.Close></div>}</Dialog.Content></Dialog.Portal></Dialog.Root></nav></div></header></>;}
export function Footer(){return <><footer className="footer"><div className="wrap footer-grid"><div><img src="/brand/logo-compacto.svg" alt="Los Compas" width="120" height="75"/><p>Buenos perros.<br/>Buena compañía.</p></div><div><h3>El parche</h3><Link href="/#menu">Nuestro menú</Link><Link href="/#domicilios">Domicilios</Link><Link href="/pagar">Tu pedido y pagos</Link></div><div><h3>Por aquí estamos</h3><p>{business.address}<br/>{business.landmark}</p><span className="delivery-label"><Bike size={16}/> Por ahora, solo domicilios</span></div></div><div className="wrap footer-bottom"><span>© {new Date().getFullYear()} Los Compas</span><span>Hecho para compartir.</span></div></footer><WhatsAppLink className="whatsapp-float"><span>Hablemos, compa <ArrowUpRight size={15}/></span></WhatsAppLink></>;}
